bitbag_sylius_cms_plugin_shop_block:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/shop/block.yml"

bitbag_sylius_cms_plugin_shop_page:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/shop/page.yml"

bitbag_sylius_cms_plugin_shop_frequently_asked_question:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/shop/frequently_asked_question.yml"

bitbag_sylius_cms_plugin_shop_section:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/shop/section.yml"