bitbag_shop_block:
    resource: "@BitBagCmsPlugin/Resources/config/routing/shop/block.yml"

bitbag_shop_page:
    resource: "@BitBagCmsPlugin/Resources/config/routing/shop/page.yml"

bitbag_shop_frequently_asked_question:
    resource: "@BitBagCmsPlugin/Resources/config/routing/shop/frequently_asked_question.yml"