services:
    bitbag_sylius_cms_plugin.menu.content_management:
        class: BitBag\SyliusCmsPlugin\Menu\ContentManagementMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

    bitbag_sylius_cms_plugin.event_listener.media_upload:
        class: BitBag\SyliusCmsPlugin\EventListener\MediaUploadListener
        arguments:
            - "@bitbag_sylius_cms_plugin.resolver.media_provider"
        tags:
            - { name: kernel.event_listener, event: bitbag_sylius_cms_plugin.media.pre_create, method: uploadMedia }
            - { name: kernel.event_listener, event: bitbag_sylius_cms_plugin.media.pre_update, method: uploadMedia }

    bitbag_sylius_cms_plugin.event_listener.package_info:
        class: BitBag\SyliusCmsPlugin\EventListener\PackageInfoListener
        tags:
            - { name: kernel.event_listener, event: kernel.finish_request, method: retrievePackageInfo }

    bitbag_sylius.event_subscriber.resource_delete:
        class: BitBag\SyliusCmsPlugin\EventListener\ResourceDeleteSubscriber
        arguments:
            - "@router"
            - "@request_stack"
        tags:
            - { name: kernel.event_subscriber, event: kernel.exception }
