services:
    bitbag_sylius_cms_plugin.menu.content_management:
        class: BitBag\SyliusCmsPlugin\Menu\ContentManagementMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

    bitbag_sylius_cms_plugin.event_listener.image_block_upload:
        class: BitBag\SyliusCmsPlugin\EventListener\ImageBlockUploadListener
        arguments:
            - "@sylius.image_uploader"
        tags:
            - { name: kernel.event_listener, event: bitbag.block.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: bitbag.block.pre_update, method: uploadImage }