services:
    bitbag_sylius_cms_plugin.importer.chain:
        class: BitBag\SyliusCmsPlugin\Importer\ImporterChain

    bitbag_sylius_cms_plugin.importer.page:
        class: BitBag\SyliusCmsPlugin\Importer\PageImporter
        arguments:
            - "@bitbag_sylius_cms_plugin.resolver.resource.page"
            - "@sylius.context.locale"
            - "@bitbag_sylius_cms_plugin.downloader.image"
            - "@bitbag_sylius_cms_plugin.factory.media"
            - "@bitbag_sylius_cms_plugin.resolver.media_provider"
            - "@bitbag_sylius_cms_plugin.resolver.importer_sections"
            - "@bitbag_sylius_cms_plugin.resolver.importer_channels"
            - "@bitbag_sylius_cms_plugin.resolver.importer_products"
            - "@validator"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: bitbag.cmsplugin.importer }

    bitbag_sylius_cms_plugin.importer.block:
        class: BitBag\SyliusCmsPlugin\Importer\BlockImporter
        arguments:
            - "@bitbag_sylius_cms_plugin.resolver.resource.block"
            - "@sylius.context.locale"
            - "@bitbag_sylius_cms_plugin.resolver.importer_sections"
            - "@bitbag_sylius_cms_plugin.resolver.importer_channels"
            - "@bitbag_sylius_cms_plugin.resolver.importer_products"
            - "@validator"
            - "@bitbag_sylius_cms_plugin.repository.block"
        tags:
            - { name: bitbag.cmsplugin.importer }

    bitbag_sylius_cms_plugin.importer.media:
        class: BitBag\SyliusCmsPlugin\Importer\MediaImporter
        arguments:
            - "@bitbag_sylius_cms_plugin.resolver.resource.media"
            - "@sylius.context.locale"
            - "@bitbag_sylius_cms_plugin.resolver.importer_sections"
            - "@bitbag_sylius_cms_plugin.resolver.importer_products"
            - "@validator"
            - "@bitbag_sylius_cms_plugin.repository.media"
        tags:
            - { name: bitbag.cmsplugin.importer }
