services:
    bitbag_sylius_cms_plugin.repository.product:
        class: BitBag\SyliusCmsPlugin\Repository\ProductRepository
        parent: sylius.repository.taxon

    bitbag_sylius_cms_plugin.repository.taxon:
        class: BitBag\SyliusCmsPlugin\Repository\TaxonRepository
        parent: sylius.repository.taxon
