imports:
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/resources/block.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/resources/page.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/resources/frequently_asked_question.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/resources/section.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/resources/media.yml" }
