sylius_grid:
    grids:
        bitbag_sylius_cms_plugin_admin_frequently_asked_question:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag_sylius_cms_plugin.model.frequently_asked_question.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                position: asc
            limits: [10, 25, 50]
            fields:
                position:
                    type: string
                    label: sylius.ui.position
                    sortable: ~
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                question:
                    type: string
                    label: bitbag_sylius_cms_plugin.ui.question
                    sortable: translation.question
                answer:
                    type: string
                    label: bitbag_sylius_cms_plugin.ui.answer
                    sortable: translation.answer
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete