Sylius\CmsPlugin\Entity\Media:
    exclusion_policy: ALL
    xml_root_name: media
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Autocomplete]
        code:
            expose: true
            type: string
            groups: [Autocomplete]
        path:
            expose: true
            type: string
            groups: [Autocomplete]
    relations:
        -
            rel: self
            href:
                route: bitbag_sylius_cms_plugin_shop_media_inline
                parameters:
                    _locale: expr(object.getTranslation().getLocale())
                    code: expr(object.getCode())
    virtual_properties:
        getName:
            serialized_name: name
            groups: [Autocomplete]
