bitbag_sylius_cms_plugin_admin_media:
    resource: |
        alias: bitbag_sylius_cms_plugin.media
        section: admin
        templates: BitBagSyliusCmsPlugin:CrudUi
        redirect: update
        grid: bitbag_sylius_cms_plugin_admin_media
        except: ['show']
        permission: true
        vars:
            all:
                header: bitbag_sylius_cms_plugin.ui.media_header
                subheader: bitbag_sylius_cms_plugin.ui.media_subheader
                templates:
                    form: "@BitBagSyliusCmsPlugin/Media/Crud/_form.html.twig"
            index:
                icon: file
    type: sylius.resource

bitbag_sylius_cms_plugin_admin_media_preview:
    path: /media/preview/{id}
    methods: [POST, PUT]
    defaults:
        _controller: bitbag_sylius_cms_plugin.controller.media:previewAction
        _sylius:
            template: "@BitBagSyliusCmsPlugin/Media/preview.html.twig"
        id: null
