bitbag_sylius_cms_plugin_admin_page:
    resource: |
        alias: bitbag_sylius_cms_plugin.page
        section: admin
        templates: BitBagSyliusCmsPlugin:CrudUi
        redirect: update
        grid: bitbag_sylius_cms_plugin_admin_page
        except: ['show']
        permission: true
        vars:
            all:
                header: bitbag_sylius_cms_plugin.ui.pages_header
                subheader: bitbag_sylius_cms_plugin.ui.pages_subheader
                templates:
                    form: BitBagSyliusCmsPlugin:Page:Crud/_form.html.twig
            index:
                icon: sticky note
    type: sylius.resource

bitbag_sylius_cms_plugin_admin_page_preview:
    path: /page/preview
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_cms_plugin.controller.page:previewAction
        _sylius:
            template: "@BitBagSyliusCmsPlugin/Shop/Page/show.html.twig"
