sylius_cms_admin_template:
    resource: |
        alias: sylius_cms.template
        section: admin
        templates: '@SyliusAdmin\\shared\\crud'
        except: ['show']
        redirect: update
        grid: sylius_cms_admin_template
        permission: true
        form:
            type: Sylius\CmsPlugin\Form\Type\TemplateType
    type: sylius.resource

sylius_cms_admin_ajax_template_page_by_name_phrase:
    path: /ajax/templates/page/search
    methods: [GET]
    defaults:
        _format: json
        _controller: sylius_cms.controller.template::indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findTemplatesByNamePart
                arguments:
                    phrase: $phrase
                    type: page

sylius_cms_admin_ajax_template_block_by_name_phrase:
    path: /ajax/templates/block/search
    methods: [GET]
    defaults:
        _format: json
        _controller: sylius_cms.controller.template::indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findTemplatesByNamePart
                arguments:
                    phrase: $phrase
                    type: block

sylius_cms_admin_ajax_template_by_id:
    path: /ajax/templates/id
    methods: [GET]
    defaults:
        _format: json
        _controller: sylius_cms.controller.template::indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: find
                arguments: [id: $id]

sylius_cms_admin_ajax_template_content_by_id:
    path: /ajax/templates/content/{id}
    methods: [GET]
    defaults:
        _format: json
        _controller: sylius_cms.controller.action.admin.template_content_elements::getContentElementsAction
        _sylius:
            permission: true
