BitBag\SyliusCmsPlugin\Entity\BlockImage:
    type: entity
    table: bitbag_block_image
    oneToOne:
        owner:
            targetEntity: BitBag\SyliusCmsPlugin\Entity\BlockTranslation
            inversedBy: image
            cascade: [ALL]
            joinColumn:
                name: owner_id
                referencedColumnName: id