BitBag\SyliusCmsPlugin\Entity\MediaTranslation:
    type: mappedSuperclass
    table: bitbag_cms_media_translation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            nullable: true
        content:
            column: content
            type: text
            nullable: true
        alt:
            column: alt
            type: text
            nullable: true
        link:
            column: link
            type: text
            nullable: true